#!/usr/bin/env python3
"""Generate the power-of-5 lookup table for Eisel-Lemire float parsing.

Produces simdjson/stage2/pow5_table.mojo with 651 entries matching
simdjson C++ power_of_five_128[].
"""

SMALLEST_POWER = -342
LARGEST_POWER = 308
NUM_ENTRIES = LARGEST_POWER - SMALLEST_POWER + 1  # 651


def compute_pow5_128():
    entries = []
    for q in range(SMALLEST_POWER, LARGEST_POWER + 1):
        if q >= 0:
            power5 = 5 ** q
        else:
            power5 = 5 ** (-q)

        num_bits = power5.bit_length()

        if q >= 0:
            # Normalize to 128 bits: shift so MSB is bit 127
            if num_bits <= 128:
                shifted = power5 << (128 - num_bits)
            else:
                shifted = power5 >> (num_bits - 128)
        else:
            # Compute ceil(2^(num_bits + 127) / power5)
            numerator = 1 << (num_bits + 127)
            shifted = numerator // power5
            if numerator % power5 != 0:
                shifted += 1  # Round up for negative exponents

        hi = (shifted >> 64) & ((1 << 64) - 1)
        lo = shifted & ((1 << 64) - 1)
        entries.append((hi, lo))
    return entries


def main():
    entries = compute_pow5_128()
    assert len(entries) == NUM_ENTRIES

    lines = []
    lines.append('"""Pre-computed power-of-5 table for Eisel-Lemire float parsing.')
    lines.append("")
    lines.append(f"651 entries for exponents {SMALLEST_POWER} to {LARGEST_POWER}.")
    lines.append("Generated by scripts/gen_pow5_table.py -- do not edit manually.")
    lines.append('"""')
    lines.append("")
    lines.append("from simdjson.stage2.eisel_lemire import Uint128")
    lines.append("")
    lines.append("")
    lines.append(f"comptime SMALLEST_POWER_OF_FIVE: Int = {SMALLEST_POWER}")
    lines.append(f"comptime LARGEST_POWER_OF_FIVE: Int = {LARGEST_POWER}")
    lines.append(f"comptime NUM_POWERS: Int = {NUM_ENTRIES}")
    lines.append("")
    lines.append("")

    # Generate the table as two functions that build Lists
    lines.append("def _init_pow5_hi() -> List[UInt64]:")
    lines.append(f"    var t = List[UInt64](capacity={NUM_ENTRIES})")
    for hi, lo in entries:
        lines.append(f"    t.append(UInt64({hi}))")
    lines.append("    return t^")
    lines.append("")
    lines.append("")
    lines.append("def _init_pow5_lo() -> List[UInt64]:")
    lines.append(f"    var t = List[UInt64](capacity={NUM_ENTRIES})")
    for hi, lo in entries:
        lines.append(f"    t.append(UInt64({lo}))")
    lines.append("    return t^")
    lines.append("")
    lines.append("")

    lines.append("def get_pow5(exponent: Int) -> Uint128:")
    lines.append('    """Get 5^exponent normalized to 128 bits."""')
    lines.append(f"    var idx = exponent - ({SMALLEST_POWER})")
    lines.append("    var hi_table = _init_pow5_hi()")
    lines.append("    var lo_table = _init_pow5_lo()")
    lines.append("    return Uint128(hi=hi_table[idx], lo=lo_table[idx])")
    lines.append("")

    with open("simdjson/stage2/pow5_table.mojo", "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {NUM_ENTRIES} entries to simdjson/stage2/pow5_table.mojo")
    # Spot checks
    print(f"5^0 (idx 342): hi=0x{entries[342][0]:016X}, lo=0x{entries[342][1]:016X}")
    print(f"5^1 (idx 343): hi=0x{entries[343][0]:016X}, lo=0x{entries[343][1]:016X}")


if __name__ == "__main__":
    main()
